@echo off
set "ANTHROPIC_AUTH_TOKEN=tp-co7hqo7902z08bm9wetz3aqobllj8johfaw1o862lba8npq0"
set "ANTHROPIC_BASE_URL=https://token-plan-cn.xiaomimimo.com/anthropic"
set "ANTHROPIC_MODEL=mimo-v2.5"
set "ANTHROPIC_DEFAULT_SONNET_MODEL=mimo-v2.5"
set "ANTHROPIC_DEFAULT_OPUS_MODEL=mimo-v2.5"
set "ANTHROPIC_DEFAULT_HAIKU_MODEL=mimo-v2.5-pro"
set "ANTHROPIC_SMALL_FAST_MODEL=mimo-v2.5-pro"
node "D:\Claude-DevSprite\dist\worker\index.js"
