@echo off
set "ANTHROPIC_AUTH_TOKEN=tp-czetsxqmkb5maksmdw18pavhqr6u0xe8i14p8mk0gc0vb9kg"
set "ANTHROPIC_BASE_URL=https://token-plan-cn.xiaomimimo.com/anthropic"
set "ANTHROPIC_MODEL=mimo-v2.5"
set "ANTHROPIC_DEFAULT_SONNET_MODEL=mimo-v2.5"
set "ANTHROPIC_DEFAULT_OPUS_MODEL=mimo-v2.5"
set "ANTHROPIC_DEFAULT_HAIKU_MODEL=mimo-v2.5-pro"
set "ANTHROPIC_SMALL_FAST_MODEL=mimo-v2.5-pro"
node "D:\Claude-DevSprite\dist\worker\index.js"
